language: elixir

elixir:
  - 1.10
  - 1.9
  - 1.8
  - 1.7
  - 1.6

before_script:
  - mix compile â€“warnings-as-errors
  - mix credo --strict
  - if [[ "$TRAVIS_ELIXIR_VERSION" =~ "1.10" ]]; then mix format mix.exs "examples/*.exs" "lib/**/*.{ex,exs}" "test/**/*.exs" --check-formatted; fi
  # - mix dialyzer

script: mix test --exclude gnuplot:true

# Remove 6min delay downloading Dialyzer dependencies
# cache:
#   directories:
#     - _build
#     - deps
